/**
 * ⚠️ 本文件由脚本自动生成，禁止手写/手改！
 * 唯一权威源：resources/scripts/montage_contract.py（default_* 骨架函数）。
 * 改动契约流程：
 *   1. 在 montage_contract.py 中增/删/改字段（含中文尾注）；
 *   2. 重新执行 `npm run gen:contracts`；
 *   3. 本文件自动同步，TS 消费端在编译期即校验字段漂移（K3 闭环）。
 * 生成命令：npm run gen:contracts
 */

/* eslint-disable */
/* generated by resources/scripts/gen_contracts.py — do not edit */

/** 剪辑装配输入契约：一条脚本句 + 其分镜工单（§8.5.5 / §24.15）。 */
export interface SegmentQuery {
  /** 段落唯一主键 */
  shotId: string;
  /** 解说词原文 */
  text: string;
  /** TTS 配音时长（刚性音频，锁定目标时长） */
  audioDurationMs: number;
  /** 原声段：锁定 ASR 原声时间窗，不配 TTS */
  keepOriginalAudio: boolean;
  /** 段落情绪标签 */
  emotion: string;
  /** VI 情绪终点态（优先于 emotion，见 KMMatchQuery） */
  moodIntent: string;
  /** 期望角色名集合（软排，Never 硬门禁） */
  characters: string[];
  /** 期望角色注册表主键集合（优先消费） */
  charIds: string[];
  /** 画面语言描述（主体/动作/场景/景别/氛围） */
  visualIntent: string;
  /** 抽象旁白路由标记（空镜分流） */
  isAbstractNarration: boolean;
  /** 显式闪回/回忆标记（豁免时序软罚） */
  isFlashback: boolean;
  /** 地点约束组名 */
  sceneGroup: string;
  /** 等分插值假锚（补丁9 提醒：勿作绝对锚） */
  startMs: number;
  durationMs: number;
  /** 段落级时间窗（Layer1） */
  windowStartMs: number;
  windowEndMs: number;
  /** 补丁9：剧情锚点（segments[sourceSceneId].startMs 查表，绝对坐标） */
  sourceRefTimeMs: number;
  /** 补丁9：语义对标场景引用（严禁手写绝对毫秒） */
  sourceSceneId: string;
  /** 真实参考帧时间（源视频绝对坐标，锁1 强锚消费） */
  refFrameTimeMs: number;
  /** matched=命中真实帧 / block_first=退化为母块首帧 / 空=无锚 */
  refFrameSource: string;
  /** 已裁片头偏移（补丁4 幻觉守卫：refFrame 落入[0,trimStartMs)判幻觉 +=trimStartMs） */
  trimStartMs: number;
  /** 源视频总时长（锁1 越界守卫：refFrame>源时长判幻觉置 0） */
  sourceDurationMs: number;
  /** 原声段 ASR 台词起始（补丁20 hasHardSub 对齐用） */
  asrAnchorStartMs: number | null;
  asrAnchorEndMs: number | null;
  /** 句尾静音气口毫秒（本句结尾→下句开头；末句为 0；None=无 ASR 气口数据） */
  silenceGapMs: any;
  matchUnitId: string;
  /** 剧情场次号（>0 时候选=该段内全部切片） */
  segmentId: number;
  /** 空间类型门禁 */
  spatialType: string;
  /** NEW_SHOT | CONTINUE_PREV */
  shotMode: string;
  /** 允许降级到第几级（降级链） */
  fallbackLevel: number;
  /** 动态门禁：动作类别 */
  actionType: string;
  /** 动态门禁：关键道具 */
  keyProp: string;
  /** 动态门禁：首选景别 */
  preferredShot: string;
  /** 补丁10：时空互文定向越狱声明 */
  isCrossSceneRecall: boolean;
  /** 补丁10：定向拉入的目标场次 */
  recallTargetSceneId: string;
}

/** 视频切片资产品牌资产（§10.2.1 A 域）：素材侧物理资产 + 视听实体字段。 */
export interface VideoChunkAsset {
  id: string;
  /** 所属物理镜头 ID（假转场识别） */
  parentChunkId: string;
  /** 物理镜头起始 */
  parentStartMs: number;
  /** 切片物理入点（source 绝对坐标） */
  startMs: number;
  /** 切片物理出点 */
  endMs: number;
  /** 素材文件路径 */
  filePath: string;
  coverPath: string;
  /** VLM 画面描述 */
  description: string;
  semantics: string;
  emotion: string;
  /** 出现角色 */
  characters: string[];
  charIds: string[];
  /** 补丁18：主控焦点角色（众数归约，frameRoles≥50%） */
  primarySubject: string;
  /** 补丁18：主控焦点置信度（出现帧率） */
  primarySubjectConf: number;
  /** 补丁14 跳轴守卫：主体视线朝向枚举 LEFT|RIGHT|FRONT|NONE（VLM 结构化标注） */
  eyelineDirection: string;
  /** 补丁17 稀有料预锁：全局唯一稀有料（求解前置 O(N) 纯统计，零模型） */
  isCriticalHeroAsset: boolean;
  /** real 实拍 / empty 空镜 / effect 特效（功能路由分流） */
  materialType: string;
  /** 可否作空镜/B-Roll（抽象句池） */
  isAbstractCapable: boolean;
  /** 是否含硬字幕（补丁20 出入点对齐 ASR 边界） */
  hasHardSub: boolean;
  /** 景别（特写/近景/中景/全景/远景/空镜） */
  shotScale: string;
  /** 机位/运镜 */
  camera: string;
  /** 服装 */
  costume: string;
  /** 地点 */
  location: string;
  /** 动静分 */
  motionScore: number;
  /** 色温直方图（补丁5 用） */
  colorHist: number[];
}

/** 宏观场次（scene）资产（S1 场记单 / §8.2 补丁19）。 */
export interface Segment {
  /** 剧情场次号（Sxx） */
  segmentId: number;
  /** 场次物理起 */
  startMs: number;
  /** 场次物理止 */
  endMs: number;
  /** 归属物理镜头集合 */
  parentIds: string[];
  /** 地点纯度 0~1（低纯度段放开空间硬卡预留） */
  locPurity: number;
  /** 场次情绪基调 */
  emotion: string;
  /** 剧情节拍描述 */
  storyBeat: string;
  /** 方向2：场次是否由 sceneCuts 自动划分（True=软偏袒源，非 Sxx 手动工单） */
  auto: boolean;
}

/** 剪辑装配引擎输入契约根（喂什么）。 */
export interface SegmentRequest {
  projectId: string;
  mediaId: string;
  /** List[SegmentQuery] */
  queries: SegmentQuery[];
  /** List[VideoChunkAsset] */
  videoChunks: VideoChunkAsset[];
  /** List[Segment] */
  segments: Segment[];
  /** {bpm, filePath, name} 或 None */
  bgm: { bpm?: number; filePath: string; name?: string } | null;
  taskId: string;
  /** on | shadow | off */
  routerMode: string;
}

/** 剪辑装配引擎输出契约（吐什么）：一段字幕一首镜的完整匹配结果，供 Node/前端渲染合成。 */
export interface MatchResult {
  /** 段落唯一主键（React key，出生处全局唯一） */
  id: string;
  /** 段落 id（与 id 同值兼容） */
  shotId: string;
  mediaId: string;
  thumbnail: string;
  /** 综合匹配得分（越大越好 / 排序键） */
  score: number;
  confirmed: boolean;
  /** K2：用户手动微调/确认后置 True（确定性锚点，重新匹配冻结） */
  isUserLocked: boolean;
  /** 命中的切片 id（chunkData 主 payload） */
  chosenChunkId: string;
  /** 补丁20：裁剪后的入场点（含 200ms 光学掐头） */
  inPointMs: number;
  /** 补丁20：裁剪后的出场点（含 200ms 光学掐尾） */
  outPointMs: number;
  /** 变速因子（[1/1.08, 1.08]，守 ±8% 铁律） */
  appliedSpeedFactor: number;
  /** 哨兵：纯裁剪段（1.00x），禁止 linear stretch */
  isExactSpeed: boolean;
  /** 配音时长 */
  audioDurationMs: number;
  /** 原始切片引用（透传） */
  chunkData: VideoChunkAsset;
  text: string;
  keepOriginalAudio: boolean;
  videoTimelineStartMs: number;
  videoTimelineEndMs: number;
  /** 降级夹杂标记（§8.2-项5 输出） */
  isDegraded: boolean;
  /** trace：本段剧情锚点（补丁9） */
  sourceRefTimeMs: number;
  /** trace：实际落到的场次（shadow 对账用） */
  assignedSegmentId: number;
  /** trace：束搜索前驱（跨场清算/诊断用） */
  prevChunkId: string;
}
